#!/bin/bash

gzip_files_in_dir() {
  cd $1
  for file in $(find . -type f)
  do
    gzip -9 -v "$file"  # Use maximum compression

    # The below creates an additional empty file named as the original
    # This might be needed for some configs and for older nginx versions
    #touch -r "$file".gz "$file"
  done
}

gzip_files_in_dir $1
